### ISSUE TITLE
NaN on timer.

### ISSUE THREAD

**Issue by GeleArthur** [GeleArthur/DashCam#10]
if in lobby and the timer gets this a input
date.setSeconds(628.490234);
crashes

**Comment by styledev** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/12783/165946018-eadf266e-0e63-4775-a80b-fc45c3915cde.png">

Console code seems to chop off milliseconds and just use seconds... it crashes the entire app?

**Comment by styledev** [comment]
Fixed in d98f5723da3a45896ff7f5d661249037e1912700
