### ISSUE TITLE
DashCam: Payload doesn't switch teams

### ISSUE THREAD

**Issue by GeleArthur** [GeleArthur/DashCam#17]

**Comment by GeleArthur** [comment]
Send over if somone switches teams

**Comment by GeleArthur** [comment]
Unable to point down what this is. I think it happends after a payload round ended and you rejoin a payload match not 100% sure

**Comment by zedrix** [comment]
It happen only on mid side switch of payload, the icons and team name are not updated correctly.
In this screenshot after the side switch, the DARK icon on the left has been updated with the correct team icon (REAL) but on the right side the name and team have not been updated
![REAL vs DARK Scrim](https://user-images.githubusercontent.com/1431129/166976502-de073734-c8ce-462d-b956-f834f7e4c0a9.JPG)

At the end of the game the two teams are reversed correctly.

**Comment by GeleArthur** [comment]
Wa wa wa WHAT this is a new one.

**Comment by GeleArthur** [comment]
This is because of the watch that doesnt work.

**Comment by GeleArthur** [comment]
Fixed with last commit
