### ISSUE TITLE
POV Helmet Issue

### ISSUE THREAD

**Issue by styledev** [GeleArthur/DashCam#41]
When spectating ichigo in ARC vs -O- third place playoffs it seems like his helmet is shown.
![E8F81DEF-5459-4A71-AF4A-2BFAA32CD744](https://user-images.githubusercontent.com/12783/178121805-43deb6c3-5bb3-48c9-a2a2-888d82e84b4d.jpeg)
![8C33822C-1782-462C-B0E1-8260FAEBD522](https://user-images.githubusercontent.com/12783/178121806-9c628e45-82a3-4ba9-8776-44a04bac267e.jpeg)

**Comment by GeleArthur** [comment]
This is also a bug that sometimes happens in hyperdash with out HyperBash

**Comment by GeleArthur** [comment]
#40 Related to

**Comment by GeleArthur** [comment]
Havent see it since
