### ISSUE TITLE
HyperBash: Fix Dashing value guessing

### ISSUE THREAD

**Issue by styledev** [GeleArthur/DashCam#8]
- ~~Sprinting dash goes to 0~~
- ~~picking up a dash doesn't give 5 dashes~~
- ~~Pressing a button doesnt give you a dash~~
- ~~Players respawn dash should reset~~
- ~~players dead dash = 0~~

**Comment by GeleArthur** [comment]
Only missing button pressing

**Comment by GeleArthur** [comment]
Fixed with 2.0.0
